rest:
  url: "https://example.org/primenumbers/v1"
  port: 8443

prime_numbers: [2, 3, 5, 7, 11, 13, 17, 19]

names:
  - Yon
  - Jon
  - Joni
  - Yoni
  - Jonatan
  - Jonathan
  - Yonatan
  - Yonathan

logistic:
  max_iter: 1000

decissionTree:
  max_depth: 4